# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\views\Qt\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/pie-chart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(56, 58, 89);\n"
"    max-width: 10px;\n"
"    margin: 10px 0 10px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #2c313c;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(98, 114, 164);\n"
"    height: 0;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(254, 121, 199);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(98, 114, 164);\n"
"    height: 0;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(254, 121, 199);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,  QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,  QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"/* Horizontal */\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color:  rgb(56, 58, 89);\n"
"    max-height: 10px;\n"
"    margin: 0 10px 0 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #2c313c;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(98, 114, 164);\n"
"    width: 0;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color: rgb(254, 121, 199);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(98, 114, 164);\n"
"    width: 0;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background-color: rgb(254, 121, 199);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,  QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,  QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"    font-family: Roboto;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"#leftMenuSubContainer {\n"
"    background-color: #16191d;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton:hover {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton {\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"#centerMenuSubContainer, #rightMenuSubContainer {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#frame_4, #frame_8 {\n"
"    background-color: #16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#frame_4 QPushButton, #frame_8 QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"#frame_4 QPushButton:hover, #frame_8 QPushButton:hover {\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"#headerContainer, #footerContainer {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#productsListContainer, #profitsFrame, #frame_16, #frame_17, #frame_18{\n"
"    border: 1px solid #2c313c;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QDoubleSpinBox {\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color: #343b47;\n"
"    color: #838ea2;\n"
"}\n"
"\n"
" #profitsFrame QPushButton,  #frame_17 QPushButton, #frame_4 QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"    background-color: #343b47;\n"
"}\n"
"\n"
" #profitsFrame QPushButton:hover,  #frame_17 QPushButton:hover, #frame_4 QPushButton:hover {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    padding: 5px;\n"
"    border-radius: 8px;\n"
"    background-color: #16191d;\n"
"    color: #838ea2;\n"
"    gridline-color: #838ea2;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #16191d;\n"
"    border: 1px solid #838ea2;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #16191d;\n"
"    border: 1px solid #838ea2;  \n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dropShadowFrame = QtWidgets.QWidget(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("#dropShadowFrame {\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dropShadowFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.dropShadowFrame)
        self.leftMenuContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.leftMenuContainer.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leftMenuContainer.setStyleSheet("")
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenuSubContainer.sizePolicy().hasHeightForWidth())
        self.leftMenuSubContainer.setSizePolicy(sizePolicy)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.frame)
        self.menuBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon1)
        self.menuBtn.setIconSize(QtCore.QSize(24, 24))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_2.addWidget(self.menuBtn)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeBtn = QtWidgets.QPushButton(self.frame_2)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeBtn.setStyleSheet("background-color: #1f232a;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon2)
        self.homeBtn.setIconSize(QtCore.QSize(24, 24))
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_3.addWidget(self.homeBtn)
        self.analisisBtn = QtWidgets.QPushButton(self.frame_2)
        self.analisisBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analisisBtn.setIcon(icon3)
        self.analisisBtn.setIconSize(QtCore.QSize(24, 24))
        self.analisisBtn.setObjectName("analisisBtn")
        self.verticalLayout_3.addWidget(self.analisisBtn)
        self.reportBtn = QtWidgets.QPushButton(self.frame_2)
        self.reportBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBtn.setIcon(icon4)
        self.reportBtn.setIconSize(QtCore.QSize(24, 24))
        self.reportBtn.setObjectName("reportBtn")
        self.verticalLayout_3.addWidget(self.reportBtn)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.simplexBtn = QtWidgets.QPushButton(self.leftMenuSubContainer)
        self.simplexBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/table.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simplexBtn.setIcon(icon5)
        self.simplexBtn.setIconSize(QtCore.QSize(24, 24))
        self.simplexBtn.setObjectName("simplexBtn")
        self.verticalLayout_2.addWidget(self.simplexBtn)
        self.frame_3 = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.leftMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(self.dropShadowFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.headerContainer = QtWidgets.QWidget(self.mainBodyContainer)
        self.headerContainer.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #343b47;\n"
"}")
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.headerContainer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/Assets/icons/pie-chart.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_6 = QtWidgets.QFrame(self.headerContainer)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(self.headerContainer)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeBtn = QtWidgets.QPushButton(self.frame_7)
        self.minimizeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeBtn.setIcon(icon6)
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_4.addWidget(self.minimizeBtn)
        self.maximizeBtn = QtWidgets.QPushButton(self.frame_7)
        self.maximizeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeBtn.setIcon(icon7)
        self.maximizeBtn.setObjectName("maximizeBtn")
        self.horizontalLayout_4.addWidget(self.maximizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.frame_7)
        self.restoreBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restoreBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon8)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_4.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame_7)
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon9)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.headerContainer, 0, QtCore.Qt.AlignTop)
        self.mainBodyContent = QtWidgets.QWidget(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContent.sizePolicy().hasHeightForWidth())
        self.mainBodyContent.setSizePolicy(sizePolicy)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mainBodyContent)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentsContainer = QtWidgets.QWidget(self.mainBodyContent)
        self.mainContentsContainer.setStyleSheet("")
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.mainContentsContainer)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.mainContentsContainer)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setStyleSheet("")
        self.homePage.setObjectName("homePage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.homeContainer = QtWidgets.QFrame(self.homePage)
        self.homeContainer.setStyleSheet("")
        self.homeContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.homeContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.homeContainer.setObjectName("homeContainer")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.homeContainer)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.productsListContainer = QtWidgets.QFrame(self.homeContainer)
        self.productsListContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.productsListContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.productsListContainer.setObjectName("productsListContainer")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.productsListContainer)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_10 = QtWidgets.QFrame(self.productsListContainer)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_26 = QtWidgets.QFrame(self.frame_10)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_9.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_9.addWidget(self.label_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem1)
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_23 = QtWidgets.QLabel(self.frame_27)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_27.addWidget(self.label_23)
        self.clavoValue = QtWidgets.QLineEdit(self.frame_27)
        self.clavoValue.setEnabled(True)
        self.clavoValue.setReadOnly(True)
        self.clavoValue.setObjectName("clavoValue")
        self.horizontalLayout_27.addWidget(self.clavoValue)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_24 = QtWidgets.QLabel(self.frame_28)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_28.addWidget(self.label_24)
        self.canelaValue = QtWidgets.QLineEdit(self.frame_28)
        self.canelaValue.setEnabled(True)
        self.canelaValue.setReadOnly(True)
        self.canelaValue.setObjectName("canelaValue")
        self.horizontalLayout_28.addWidget(self.canelaValue)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem3)
        self.verticalLayout_9.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_25 = QtWidgets.QLabel(self.frame_29)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_29.addWidget(self.label_25)
        self.uvaValue = QtWidgets.QLineEdit(self.frame_29)
        self.uvaValue.setEnabled(True)
        self.uvaValue.setReadOnly(True)
        self.uvaValue.setObjectName("uvaValue")
        self.horizontalLayout_29.addWidget(self.uvaValue)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_26)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_26 = QtWidgets.QLabel(self.frame_30)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_30.addWidget(self.label_26)
        self.ajoValue = QtWidgets.QLineEdit(self.frame_30)
        self.ajoValue.setReadOnly(True)
        self.ajoValue.setObjectName("ajoValue")
        self.horizontalLayout_30.addWidget(self.ajoValue)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.frame_30)
        self.verticalLayout_11.addWidget(self.frame_26)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_8.addItem(spacerItem6)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.clavoDual = QtWidgets.QLineEdit(self.frame_12)
        self.clavoDual.setEnabled(True)
        self.clavoDual.setReadOnly(True)
        self.clavoDual.setObjectName("clavoDual")
        self.horizontalLayout_15.addWidget(self.clavoDual)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_8.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.frame_13)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.canelaDual = QtWidgets.QLineEdit(self.frame_13)
        self.canelaDual.setEnabled(True)
        self.canelaDual.setReadOnly(True)
        self.canelaDual.setObjectName("canelaDual")
        self.horizontalLayout_16.addWidget(self.canelaDual)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.verticalLayout_8.addWidget(self.frame_13)
        self.frame_25 = QtWidgets.QFrame(self.frame_11)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.frame_25)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.uvaDual = QtWidgets.QLineEdit(self.frame_25)
        self.uvaDual.setEnabled(True)
        self.uvaDual.setReadOnly(True)
        self.uvaDual.setObjectName("uvaDual")
        self.horizontalLayout_17.addWidget(self.uvaDual)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_8.addWidget(self.frame_25)
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.frame_14)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.ajoDual = QtWidgets.QLineEdit(self.frame_14)
        self.ajoDual.setReadOnly(True)
        self.ajoDual.setObjectName("ajoDual")
        self.horizontalLayout_18.addWidget(self.ajoDual)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout_8.addWidget(self.frame_14)
        self.verticalLayout_11.addWidget(self.frame_11)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.horizontalLayout_14.addWidget(self.frame_10)
        self.horizontalLayout_12.addWidget(self.productsListContainer)
        self.resumeContainer = QtWidgets.QFrame(self.homeContainer)
        self.resumeContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resumeContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resumeContainer.setObjectName("resumeContainer")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.resumeContainer)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.profitsFrame = QtWidgets.QFrame(self.resumeContainer)
        self.profitsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profitsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profitsFrame.setObjectName("profitsFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.profitsFrame)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.profitsFrame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.profitValue = QtWidgets.QLineEdit(self.profitsFrame)
        self.profitValue.setEnabled(True)
        self.profitValue.setReadOnly(True)
        self.profitValue.setObjectName("profitValue")
        self.horizontalLayout_13.addWidget(self.profitValue)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.viewSimplexBtn = QtWidgets.QPushButton(self.profitsFrame)
        self.viewSimplexBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewSimplexBtn.setIcon(icon5)
        self.viewSimplexBtn.setObjectName("viewSimplexBtn")
        self.horizontalLayout_13.addWidget(self.viewSimplexBtn)
        self.generateReportBtn = QtWidgets.QPushButton(self.profitsFrame)
        self.generateReportBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateReportBtn.setIcon(icon4)
        self.generateReportBtn.setObjectName("generateReportBtn")
        self.horizontalLayout_13.addWidget(self.generateReportBtn)
        self.verticalLayout_20.addWidget(self.profitsFrame, 0, QtCore.Qt.AlignTop)
        self.graphic = QtWidgets.QVBoxLayout()
        self.graphic.setObjectName("graphic")
        self.verticalLayout_20.addLayout(self.graphic)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_20.setStretch(1, 9)
        self.horizontalLayout_12.addWidget(self.resumeContainer)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 7)
        self.verticalLayout_16.addWidget(self.homeContainer)
        self.stackedWidget_3.addWidget(self.homePage)
        self.analisisPage = QtWidgets.QWidget()
        self.analisisPage.setObjectName("analisisPage")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.analisisPage)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.analisisContainer = QtWidgets.QWidget(self.analisisPage)
        self.analisisContainer.setObjectName("analisisContainer")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.analisisContainer)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_15 = QtWidgets.QFrame(self.analisisContainer)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_24.setContentsMargins(16, -1, 16, -1)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_22 = QtWidgets.QFrame(self.frame_17)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.options = QtWidgets.QComboBox(self.frame_22)
        self.options.setObjectName("options")
        self.horizontalLayout_20.addWidget(self.options)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.verticalLayout_24.addWidget(self.frame_22)
        self.frame_24 = QtWidgets.QFrame(self.frame_17)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_22 = QtWidgets.QLabel(self.frame_24)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_26.addWidget(self.label_22)
        self.items = QtWidgets.QComboBox(self.frame_24)
        self.items.setObjectName("items")
        self.horizontalLayout_26.addWidget(self.items)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem14)
        self.verticalLayout_24.addWidget(self.frame_24)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.frame_19)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.elementValue = QtWidgets.QLineEdit(self.frame_19)
        self.elementValue.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elementValue.sizePolicy().hasHeightForWidth())
        self.elementValue.setSizePolicy(sizePolicy)
        self.elementValue.setInputMask("")
        self.elementValue.setReadOnly(True)
        self.elementValue.setObjectName("elementValue")
        self.horizontalLayout_21.addWidget(self.elementValue)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem15)
        self.verticalLayout_24.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        self.underLimit = QtWidgets.QLineEdit(self.frame_20)
        self.underLimit.setEnabled(True)
        self.underLimit.setReadOnly(True)
        self.underLimit.setObjectName("underLimit")
        self.horizontalLayout_22.addWidget(self.underLimit)
        self.label = QtWidgets.QLabel(self.frame_20)
        self.label.setObjectName("label")
        self.horizontalLayout_22.addWidget(self.label)
        self.newValue = QtWidgets.QDoubleSpinBox(self.frame_20)
        self.newValue.setObjectName("newValue")
        self.horizontalLayout_22.addWidget(self.newValue)
        self.label_3 = QtWidgets.QLabel(self.frame_20)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_22.addWidget(self.label_3)
        self.overLimit = QtWidgets.QLineEdit(self.frame_20)
        self.overLimit.setEnabled(True)
        self.overLimit.setReadOnly(True)
        self.overLimit.setObjectName("overLimit")
        self.horizontalLayout_22.addWidget(self.overLimit)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem16)
        self.verticalLayout_24.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.simulateBtn = QtWidgets.QPushButton(self.frame_21)
        self.simulateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.simulateBtn.setIcon(icon3)
        self.simulateBtn.setObjectName("simulateBtn")
        self.horizontalLayout_23.addWidget(self.simulateBtn)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.verticalLayout_24.addWidget(self.frame_21)
        self.horizontalLayout_19.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.horizontalLayout_19.addWidget(self.frame_18)
        self.horizontalLayout_19.setStretch(0, 5)
        self.horizontalLayout_19.setStretch(1, 6)
        self.verticalLayout_22.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.analisisContainer)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.textEdit = QtWidgets.QTextEdit(self.frame_16)
        self.textEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_24.addWidget(self.textEdit)
        self.verticalLayout_22.addWidget(self.frame_16)
        self.verticalLayout_22.setStretch(0, 6)
        self.verticalLayout_22.setStretch(1, 5)
        self.verticalLayout_17.addWidget(self.analisisContainer)
        self.stackedWidget_3.addWidget(self.analisisPage)
        self.reportsPage = QtWidgets.QWidget()
        self.reportsPage.setObjectName("reportsPage")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.reportsPage)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.reportContainer = QtWidgets.QWidget(self.reportsPage)
        self.reportContainer.setObjectName("reportContainer")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.reportContainer)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.reportArea = QtWidgets.QScrollArea(self.reportContainer)
        self.reportArea.setWidgetResizable(True)
        self.reportArea.setObjectName("reportArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 859, 446))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_31 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.reportText = QtWidgets.QTextEdit(self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.reportText.setFont(font)
        self.reportText.setStyleSheet("#reportText {\n"
"font-weight: regular;\n"
"}")
        self.reportText.setReadOnly(True)
        self.reportText.setObjectName("reportText")
        self.horizontalLayout_32.addWidget(self.reportText)
        self.frame_32 = QtWidgets.QFrame(self.frame_31)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.reportGraphic = QtWidgets.QVBoxLayout()
        self.reportGraphic.setObjectName("reportGraphic")
        self.verticalLayout_14.addLayout(self.reportGraphic)
        self.horizontalLayout_32.addWidget(self.frame_32)
        self.horizontalLayout_32.setStretch(0, 5)
        self.horizontalLayout_32.setStretch(1, 5)
        self.verticalLayout_12.addWidget(self.frame_31)
        self.reportArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_31.addWidget(self.reportArea)
        self.verticalLayout_18.addWidget(self.reportContainer)
        self.stackedWidget_3.addWidget(self.reportsPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.frame_23 = QtWidgets.QFrame(self.frame_8)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.fase = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fase.setFont(font)
        self.fase.setObjectName("fase")
        self.horizontalLayout_25.addWidget(self.fase)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem19)
        self.label2 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.horizontalLayout_25.addWidget(self.label2)
        self.iteration = QtWidgets.QLabel(self.frame_23)
        self.iteration.setObjectName("iteration")
        self.horizontalLayout_25.addWidget(self.iteration)
        self.verticalLayout_7.addWidget(self.frame_23)
        self.widget = QtWidgets.QWidget(self.frame_8)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/Assets/icons/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon11)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.verticalLayout_7.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.stackedWidget_3.addWidget(self.page)
        self.verticalLayout_15.addWidget(self.stackedWidget_3)
        self.horizontalLayout_8.addWidget(self.mainContentsContainer)
        self.verticalLayout_10.addWidget(self.mainBodyContent)
        self.footerContainer = QtWidgets.QWidget(self.mainBodyContainer)
        self.footerContainer.setObjectName("footerContainer")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.footerContainer)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.footerContainer)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-weigth: 500;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.horizontalLayout_10.addWidget(self.frame_9)
        self.verticalLayout_10.addWidget(self.footerContainer)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        self.verticalLayout_6.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Análisis App"))
        self.menuBtn.setToolTip(_translate("MainWindow", "Menu"))
        self.homeBtn.setToolTip(_translate("MainWindow", "Inicio"))
        self.homeBtn.setText(_translate("MainWindow", "Inicio"))
        self.analisisBtn.setToolTip(_translate("MainWindow", "Realizar Simulaciones"))
        self.analisisBtn.setText(_translate("MainWindow", "Análisis"))
        self.reportBtn.setToolTip(_translate("MainWindow", "Ver Reportes"))
        self.reportBtn.setText(_translate("MainWindow", "Reportes"))
        self.simplexBtn.setToolTip(_translate("MainWindow", "Ver Reportes"))
        self.simplexBtn.setText(_translate("MainWindow", "Tableros"))
        self.label_6.setText(_translate("MainWindow", "ANÁLISIS APP"))
        self.minimizeBtn.setToolTip(_translate("MainWindow", "Minimizar"))
        self.maximizeBtn.setToolTip(_translate("MainWindow", "Restaurar"))
        self.restoreBtn.setToolTip(_translate("MainWindow", "Restaurar"))
        self.closeBtn.setToolTip(_translate("MainWindow", "Cerrar"))
        self.label_21.setText(_translate("MainWindow", "PRODUCTOS"))
        self.label_23.setText(_translate("MainWindow", "Clavo:"))
        self.clavoValue.setText(_translate("MainWindow", "$ 0"))
        self.label_24.setText(_translate("MainWindow", "Canela:"))
        self.canelaValue.setText(_translate("MainWindow", "$ 0"))
        self.label_25.setText(_translate("MainWindow", "Uva Pasa:"))
        self.uvaValue.setText(_translate("MainWindow", "$ 0"))
        self.label_26.setText(_translate("MainWindow", "Ajo Sal:"))
        self.ajoValue.setText(_translate("MainWindow", "$ 0"))
        self.label_14.setText(_translate("MainWindow", "PRECIOS DUALES"))
        self.label_16.setText(_translate("MainWindow", "Clavo:"))
        self.clavoDual.setText(_translate("MainWindow", "$ 0"))
        self.label_17.setText(_translate("MainWindow", "Canela:"))
        self.canelaDual.setText(_translate("MainWindow", "$ 0"))
        self.label_18.setText(_translate("MainWindow", "Uva Pasa:"))
        self.uvaDual.setText(_translate("MainWindow", "$ 0"))
        self.label_19.setText(_translate("MainWindow", "Ajo Sal:"))
        self.ajoDual.setText(_translate("MainWindow", "$ 0"))
        self.label_10.setText(_translate("MainWindow", "Utilidad:"))
        self.profitValue.setText(_translate("MainWindow", "$ 0"))
        self.viewSimplexBtn.setToolTip(_translate("MainWindow", "Ver Tableros Simplex"))
        self.viewSimplexBtn.setText(_translate("MainWindow", "Tableros"))
        self.generateReportBtn.setToolTip(_translate("MainWindow", "Ver Reporte"))
        self.generateReportBtn.setText(_translate("MainWindow", "Reporte"))
        self.label_11.setText(_translate("MainWindow", "Elemento:"))
        self.label_22.setText(_translate("MainWindow", "Producto:"))
        self.label_15.setText(_translate("MainWindow", "Valor Actual:"))
        self.elementValue.setText(_translate("MainWindow", "$ "))
        self.label_20.setText(_translate("MainWindow", "Nuevo Valor:"))
        self.underLimit.setText(_translate("MainWindow", "$ 0"))
        self.label.setText(_translate("MainWindow", "<="))
        self.newValue.setPrefix(_translate("MainWindow", "$ "))
        self.label_3.setText(_translate("MainWindow", "<="))
        self.overLimit.setText(_translate("MainWindow", "$ 0"))
        self.simulateBtn.setToolTip(_translate("MainWindow", "Realizar Simulación"))
        self.simulateBtn.setText(_translate("MainWindow", "Simular"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Simplex Dos Fases"))
        self.fase.setText(_translate("MainWindow", "Fase 1"))
        self.label2.setText(_translate("MainWindow", "Iteración"))
        self.iteration.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Siguiente Tablero"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Siguiente Tablero"))
        self.label_13.setText(_translate("MainWindow", "<strong>Desarrollado por:</strong> Kevin Santiago Martinez - Joshep Mateo Granada"))
import views.resources_rc
